/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum IpVersion {
  V4 = 0,
  V6 = 1,
  Any = 2
}
export const enum Strategy {
  First = 0,
  Race = 1,
  Consensus = 2
}
export const enum Protocol {
  Dns = 0,
  Http = 1,
  Stun = 2
}
export const enum BuiltinProvider {
  GoogleStun = 0,
  GoogleStun1 = 1,
  GoogleStun2 = 2,
  CloudflareStun = 3,
  GoogleDns = 4,
  CloudflareDns = 5,
  OpenDns = 6,
  CloudflareHttp = 7,
  Aws = 8
}
export interface JsProviderResult {
  ip: string
  provider: string
  protocol: string
  latencyMs: number
}
export interface JsConfig {
  timeoutMs?: number
  version?: IpVersion
  strategy?: Strategy
  protocols?: Array<Protocol>
  providers?: Array<BuiltinProvider>
}
export declare function getIp(config?: JsConfig | undefined | null): Promise<JsProviderResult>
export declare function getIpv4(): Promise<JsProviderResult>
export declare function getIpv6(): Promise<JsProviderResult>
export declare function getPrivateIp(): string | null
export declare function getPrivateIpv6(): string | null
